# cri_socket=unix:///var/run/crio/crio.sock
# cri_socket=unix:///run/containerd/containerd.sock
# cri_socket=unix:///var/run/cri-dockerd.sock

- hosts: all
  become: yes
  become_user: root
  user: ubuntu
  tasks:
    - name: set globals
      set_fact:
        interface=enp1s0
        cp_endpoint_ip=192.168.122.191
        cp_endpoint=mycluster-cp
        k8s_version=1.24.3
        pod_network_cidr=172.16.0.0/16
        service_cidr=10.96.0.0/12
        cri_socket=unix:///run/containerd/containerd.sock

